import bcrypt from 'bcryptjs';
import { IUser, IVessel, IVoyage, ICargo, IFuelRecord, IMaintenance, IPort, ICrew, IAlert, IAuditLog } from './types.ts';

const hashPassword = (pw: string) => bcrypt.hashSync(pw, 10);

export const seedUsers: IUser[] = [
  {
    _id: 'usr_admin_001',
    name: 'Captain Marcus Vance (Admin)',
    email: 'admin@shipfleet.com',
    password: hashPassword('Admin@123'),
    role: 'admin',
    status: 'active',
    department: 'Fleet Operations Directorate',
    lastLogin: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'usr_admin_fleetops',
    name: 'Fleet Administrator',
    email: 'admin@fleetops.com',
    password: hashPassword('Admin@123'),
    role: 'admin',
    status: 'active',
    department: 'Executive Maritime Command',
    lastLogin: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'usr_user_001',
    name: 'Elena Rostova (User)',
    email: 'user@shipfleet.com',
    password: hashPassword('User@123'),
    role: 'user',
    status: 'active',
    department: 'Fleet Operations & Voyage Control',
    lastLogin: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'usr_user_fleetops',
    name: 'Operations User',
    email: 'user@fleetops.com',
    password: hashPassword('User@123'),
    role: 'user',
    status: 'active',
    department: 'Voyage Dispatch & Cargo Control',
    lastLogin: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'usr_operator_001',
    name: 'Operations & Dispatch User',
    email: 'operator@shipfleet.com',
    password: hashPassword('User@123'),
    role: 'user',
    status: 'active',
    department: 'Voyage Dispatch Center',
    lastLogin: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'usr_viewer_001',
    name: 'Monitoring & Audit User',
    email: 'viewer@shipfleet.com',
    password: hashPassword('User@123'),
    role: 'user',
    status: 'active',
    department: 'Cargo Auditing & Client Oversight',
    lastLogin: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: new Date('2025-02-01').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedPorts: IPort[] = [
  {
    _id: 'prt_rotterdam',
    portId: 'PRT-NLRTM',
    name: 'Port of Rotterdam',
    country: 'Netherlands',
    city: 'Rotterdam',
    portCode: 'NLRTM',
    lat: 51.95,
    lng: 4.13,
    capacityTEU: 15300000,
    contact: '+31 10 252 1010 / ops@portofrotterdam.nl',
    operatingHours: '24/7 Continuous All Weather',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_singapore',
    portId: 'PRT-SGSIN',
    name: 'Port of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    portCode: 'SGSIN',
    lat: 1.28,
    lng: 103.85,
    capacityTEU: 37200000,
    contact: '+65 6375 1600 / marine@mpa.gov.sg',
    operatingHours: '24/7 Continuous',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_shanghai',
    portId: 'PRT-CNSHA',
    name: 'Port of Shanghai',
    country: 'China',
    city: 'Shanghai',
    portCode: 'CNSHA',
    lat: 31.23,
    lng: 121.47,
    capacityTEU: 47300000,
    contact: '+86 21 6329 1222 / dispatch@portshanghai.com',
    operatingHours: '24/7 Continuous',
    status: 'Congested',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_losangeles',
    portId: 'PRT-USLAX',
    name: 'Port of Los Angeles',
    country: 'United States',
    city: 'Los Angeles',
    portCode: 'USLAX',
    lat: 33.74,
    lng: -118.26,
    capacityTEU: 10600000,
    contact: '+1 310 732 3508 / ops@portla.org',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_jebelali',
    portId: 'PRT-AEJEA',
    name: 'Port of Jebel Ali (Dubai)',
    country: 'United Arab Emirates',
    city: 'Dubai',
    portCode: 'AEJEA',
    lat: 25.01,
    lng: 55.06,
    capacityTEU: 14100000,
    contact: '+971 4 881 5555 / info@dpworld.com',
    operatingHours: '24/7 Continuous',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_hamburg',
    portId: 'PRT-DEHAM',
    name: 'Port of Hamburg',
    country: 'Germany',
    city: 'Hamburg',
    portCode: 'DEHAM',
    lat: 53.54,
    lng: 9.98,
    capacityTEU: 8700000,
    contact: '+49 40 42847 0 / leitzentrale@hpa.hamburg.de',
    operatingHours: '24/7 Continuous',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_busan',
    portId: 'PRT-KRPUS',
    name: 'Port of Busan',
    country: 'South Korea',
    city: 'Busan',
    portCode: 'KRPUS',
    lat: 35.10,
    lng: 129.04,
    capacityTEU: 22700000,
    contact: '+82 51 999 3000 / master@busanpa.com',
    operatingHours: '24/7 Continuous',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_antwerp',
    portId: 'PRT-BEANR',
    name: 'Port of Antwerp-Bruges',
    country: 'Belgium',
    city: 'Antwerp',
    portCode: 'BEANR',
    lat: 51.26,
    lng: 4.38,
    capacityTEU: 13500000,
    contact: '+32 3 205 2011 / communications@portofantwerpbruges.com',
    operatingHours: '24/7 Continuous',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_santos',
    portId: 'PRT-BRSSZ',
    name: 'Port of Santos',
    country: 'Brazil',
    city: 'Santos',
    portCode: 'BRSSZ',
    lat: -23.96,
    lng: -46.31,
    capacityTEU: 4800000,
    contact: '+55 13 3202 6565 / santosport@portodesantos.gov.br',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_yokohama',
    portId: 'PRT-JPYOK',
    name: 'Port of Yokohama',
    country: 'Japan',
    city: 'Yokohama',
    portCode: 'JPYOK',
    lat: 35.45,
    lng: 139.65,
    capacityTEU: 3100000,
    contact: '+81 45 671 7188 / port@city.yokohama.jp',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_panama',
    portId: 'PRT-PAPTY',
    name: 'Port of Balboa (Panama Canal)',
    country: 'Panama',
    city: 'Panama City',
    portCode: 'PAPTY',
    lat: 8.95,
    lng: -79.56,
    capacityTEU: 3500000,
    contact: '+507 272 4570 / ops@pancanal.com',
    operatingHours: '24/7 Canal Transit',
    status: 'Restricted',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_suez',
    portId: 'PRT-EGSUZ',
    name: 'Port of Port Said (Suez Canal)',
    country: 'Egypt',
    city: 'Port Said',
    portCode: 'EGSUZ',
    lat: 31.26,
    lng: 32.30,
    capacityTEU: 4000000,
    contact: '+20 66 322 2222 / maritime@suezcanal.gov.eg',
    operatingHours: '24/7 Convoy Transit',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_houston',
    portId: 'PRT-USHOU',
    name: 'Port of Houston',
    country: 'United States',
    city: 'Houston',
    portCode: 'USHOU',
    lat: 29.74,
    lng: -95.27,
    capacityTEU: 3800000,
    contact: '+1 713 670 2400 / operations@porthouston.com',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_felixstowe',
    portId: 'PRT-GBFXT',
    name: 'Port of Felixstowe',
    country: 'United Kingdom',
    city: 'Felixstowe',
    portCode: 'GBFXT',
    lat: 51.95,
    lng: 1.31,
    capacityTEU: 4000000,
    contact: '+44 1394 604500 / maritime@portoffelixstowe.co.uk',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prt_valencia',
    portId: 'PRT-ESVLC',
    name: 'Port of Valencia',
    country: 'Spain',
    city: 'Valencia',
    portCode: 'ESVLC',
    lat: 39.45,
    lng: -0.32,
    capacityTEU: 5400000,
    contact: '+34 96 393 9400 / apv@valenciaport.com',
    operatingHours: '24/7 Operations',
    status: 'Open',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedVessels: IVessel[] = [
  {
    _id: 'vsl_001',
    vesselId: 'VSL-101',
    imoNumber: 'IMO9839438',
    name: 'MV Ocean Star',
    vesselType: 'Container Ship',
    flag: 'Panama',
    owner: 'FleetOps Global Ocean Line',
    captain: 'Capt. Henrik Lindqvist',
    capacity: 21500, // TEU
    deadweightTonnage: 218000,
    grossTonnage: 210000,
    length: 399.9,
    width: 61.3,
    draft: 16.5,
    engineType: 'MAN B&W 11G95ME-C9.5',
    enginePower: 75570,
    fuelType: 'VLSFO',
    fuelCapacity: 12500,
    currentFuel: 8420,
    currentLocation: {
      lat: 22.45,
      lng: 68.32,
      portOrArea: 'Arabian Sea / Trans-Indian Ocean Route',
      speedKnots: 18.4,
      heading: 112,
      updatedAt: new Date().toISOString()
    },
    status: 'In Transit',
    yearBuilt: 2021,
    lastInspection: '2025-11-14',
    nextInspection: '2026-11-14',
    insuranceExpiry: '2027-04-30',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_002',
    vesselId: 'VSL-102',
    imoNumber: 'IMO9776418',
    name: 'MV Pacific Titan',
    vesselType: 'Bulk Carrier',
    flag: 'Liberia',
    owner: 'FleetOps Bulkers Int.',
    captain: 'Capt. Arthur Pendelton',
    capacity: 180000, // DWT
    deadweightTonnage: 181200,
    grossTonnage: 95400,
    length: 292.0,
    width: 45.0,
    draft: 18.2,
    engineType: 'Hyundai-MAN B&W 6S70ME-C8',
    enginePower: 21500,
    fuelType: 'VLSFO',
    fuelCapacity: 5200,
    currentFuel: 950, // Low fuel alert trigger
    currentLocation: {
      lat: 34.20,
      lng: 135.10,
      portOrArea: 'Approaching Port of Yokohama / Kii Channel',
      speedKnots: 12.8,
      heading: 54,
      updatedAt: new Date().toISOString()
    },
    status: 'In Transit',
    yearBuilt: 2018,
    lastInspection: '2025-08-20',
    nextInspection: '2026-08-20',
    insuranceExpiry: '2026-12-31',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_003',
    vesselId: 'VSL-103',
    imoNumber: 'IMO9682540',
    name: 'MT Arctic Voyager',
    vesselType: 'LNG Carrier',
    flag: 'Marshall Islands',
    owner: 'FleetOps Energy Transport',
    captain: 'Capt. Valery Morozov',
    capacity: 174000, // CBM
    deadweightTonnage: 98000,
    grossTonnage: 115000,
    length: 299.0,
    width: 46.4,
    draft: 12.0,
    engineType: 'WinGD X-DF Dual-Fuel Low Pressure Gas',
    enginePower: 34200,
    fuelType: 'LNG',
    fuelCapacity: 8000,
    currentFuel: 6800,
    currentLocation: {
      lat: 51.95,
      lng: 4.13,
      portOrArea: 'Port of Rotterdam - Gate Terminal Quay 4',
      speedKnots: 0.0,
      heading: 270,
      updatedAt: new Date().toISOString()
    },
    status: 'Docked',
    yearBuilt: 2022,
    lastInspection: '2026-01-10',
    nextInspection: '2027-01-10',
    insuranceExpiry: '2027-06-15',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_004',
    vesselId: 'VSL-104',
    imoNumber: 'IMO9845124',
    name: 'MT Atlantic Pioneer',
    vesselType: 'Oil Tanker',
    flag: 'Bahamas',
    owner: 'FleetOps Global Tankers',
    captain: 'Capt. Carlos Mendez',
    capacity: 318000, // DWT VLCC
    deadweightTonnage: 319500,
    grossTonnage: 162000,
    length: 333.0,
    width: 60.0,
    draft: 22.5,
    engineType: 'Wartsila 7X82-B',
    enginePower: 29800,
    fuelType: 'VLSFO',
    fuelCapacity: 6400,
    currentFuel: 3200,
    currentLocation: {
      lat: 25.01,
      lng: 55.06,
      portOrArea: 'Jebel Ali Anchorage / Arabian Gulf',
      speedKnots: 0.0,
      heading: 180,
      updatedAt: new Date().toISOString()
    },
    status: 'Maintenance',
    yearBuilt: 2019,
    lastInspection: '2025-05-18',
    nextInspection: '2026-05-18', // overdue or due soon
    insuranceExpiry: '2026-11-01',
    createdAt: new Date('2024-02-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_005',
    vesselId: 'VSL-105',
    imoNumber: 'IMO9912456',
    name: 'MV Nordic Explorer',
    vesselType: 'Container Ship',
    flag: 'Denmark',
    owner: 'FleetOps European Feeder',
    captain: 'Capt. Jens Sorensen',
    capacity: 8500, // TEU
    deadweightTonnage: 104000,
    grossTonnage: 92000,
    length: 299.8,
    width: 48.2,
    draft: 14.5,
    engineType: 'MAN B&W 8G80ME-C9.2',
    enginePower: 42000,
    fuelType: 'MGO',
    fuelCapacity: 4500,
    currentFuel: 3800,
    currentLocation: {
      lat: 53.54,
      lng: 9.98,
      portOrArea: 'Port of Hamburg - Waltershof Terminal',
      speedKnots: 0.0,
      heading: 90,
      updatedAt: new Date().toISOString()
    },
    status: 'Active',
    yearBuilt: 2023,
    lastInspection: '2026-03-01',
    nextInspection: '2027-03-01',
    insuranceExpiry: '2027-09-30',
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_006',
    vesselId: 'VSL-106',
    imoNumber: 'IMO9754321',
    name: 'MV Southern Cross',
    vesselType: 'General Cargo',
    flag: 'Singapore',
    owner: 'FleetOps Regional Lines',
    captain: 'Capt. Tan Wei Ming',
    capacity: 35000, // DWT
    deadweightTonnage: 35500,
    grossTonnage: 24200,
    length: 179.9,
    width: 28.4,
    draft: 10.2,
    engineType: 'Mitsui-MAN B&W 6S46ME-B8.5',
    enginePower: 7900,
    fuelType: 'VLSFO',
    fuelCapacity: 1800,
    currentFuel: 1250,
    currentLocation: {
      lat: -8.15,
      lng: 115.20,
      portOrArea: 'Java Sea / Lombok Strait Passage',
      speedKnots: 14.2,
      heading: 198,
      updatedAt: new Date().toISOString()
    },
    status: 'In Transit',
    yearBuilt: 2017,
    lastInspection: '2025-09-10',
    nextInspection: '2026-09-10',
    insuranceExpiry: '2026-10-15',
    createdAt: new Date('2024-03-10').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_007',
    vesselId: 'VSL-107',
    imoNumber: 'IMO9892011',
    name: 'MV Baltic Navigator',
    vesselType: 'Bulk Carrier',
    flag: 'Cyprus',
    owner: 'FleetOps Grain Logistics',
    captain: 'Capt. Nikos Papadopoulos',
    capacity: 82000, // Kamsarmax
    deadweightTonnage: 82500,
    grossTonnage: 44000,
    length: 229.0,
    width: 32.26,
    draft: 14.45,
    engineType: 'Doosan-MAN B&W 6S60ME-C8.2',
    enginePower: 12800,
    fuelType: 'VLSFO',
    fuelCapacity: 2600,
    currentFuel: 1840,
    currentLocation: {
      lat: -23.96,
      lng: -46.31,
      portOrArea: 'Port of Santos - Grain Terminal 2',
      speedKnots: 0.0,
      heading: 45,
      updatedAt: new Date().toISOString()
    },
    status: 'Docked',
    yearBuilt: 2020,
    lastInspection: '2025-10-22',
    nextInspection: '2026-10-22',
    insuranceExpiry: '2027-02-28',
    createdAt: new Date('2024-03-20').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_008',
    vesselId: 'VSL-108',
    imoNumber: 'IMO9948203',
    name: 'MV Global Horizon',
    vesselType: 'Container Ship',
    flag: 'Panama',
    owner: 'FleetOps Global Ocean Line',
    captain: 'Capt. Liam O\'Connor',
    capacity: 24000, // Mega Max
    deadweightTonnage: 232000,
    grossTonnage: 235000,
    length: 400.0,
    width: 61.5,
    draft: 17.0,
    engineType: 'WinGD 12X92DF Dual-Fuel',
    enginePower: 85000,
    fuelType: 'LNG',
    fuelCapacity: 18600,
    currentFuel: 14200,
    currentLocation: {
      lat: 29.80,
      lng: -140.20,
      portOrArea: 'Mid-Pacific Great Circle Track (Eastbound)',
      speedKnots: 19.5,
      heading: 84,
      updatedAt: new Date().toISOString()
    },
    status: 'In Transit',
    yearBuilt: 2024,
    lastInspection: '2026-02-15',
    nextInspection: '2027-02-15',
    insuranceExpiry: '2028-01-31',
    createdAt: new Date('2024-04-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_009',
    vesselId: 'VSL-109',
    imoNumber: 'IMO9621456',
    name: 'MT Coral Seaways',
    vesselType: 'Oil Tanker',
    flag: 'Malta',
    owner: 'FleetOps Mediterranean Clean Fuels',
    captain: 'Capt. Giuseppe Moretti',
    capacity: 115000, // Aframax
    deadweightTonnage: 114800,
    grossTonnage: 62000,
    length: 249.9,
    width: 44.0,
    draft: 15.0,
    engineType: 'MAN B&W 6S60ME-C',
    enginePower: 14200,
    fuelType: 'VLSFO',
    fuelCapacity: 3200,
    currentFuel: 2100,
    currentLocation: {
      lat: 36.14,
      lng: -5.35,
      portOrArea: 'Strait of Gibraltar (Westbound)',
      speedKnots: 13.5,
      heading: 265,
      updatedAt: new Date().toISOString()
    },
    status: 'In Transit',
    yearBuilt: 2016,
    lastInspection: '2025-07-15',
    nextInspection: '2026-07-15',
    insuranceExpiry: '2026-11-20',
    createdAt: new Date('2024-04-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vsl_010',
    vesselId: 'VSL-110',
    imoNumber: 'IMO9587421',
    name: 'MV Pioneer Trader',
    vesselType: 'General Cargo',
    flag: 'Antigua and Barbuda',
    owner: 'FleetOps Caribbean feeder',
    captain: 'Capt. Franklin Brooks',
    capacity: 22000,
    deadweightTonnage: 21900,
    grossTonnage: 16500,
    length: 159.0,
    width: 24.5,
    draft: 8.8,
    engineType: 'Mak 9M43C',
    enginePower: 8400,
    fuelType: 'MGO',
    fuelCapacity: 1400,
    currentFuel: 800,
    currentLocation: {
      lat: 29.74,
      lng: -95.27,
      portOrArea: 'Port of Houston Turning Basin',
      speedKnots: 0.0,
      heading: 0,
      updatedAt: new Date().toISOString()
    },
    status: 'Idle',
    yearBuilt: 2014,
    lastInspection: '2025-12-05',
    nextInspection: '2026-12-05',
    insuranceExpiry: '2027-01-15',
    createdAt: new Date('2024-05-01').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedVoyages: IVoyage[] = [
  {
    _id: 'vyg_001',
    voyageId: 'VYG-1001',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    originPort: 'Port of Rotterdam',
    originPortCode: 'NLRTM',
    originCoords: [51.95, 4.13],
    destinationPort: 'Port of Singapore',
    destinationPortCode: 'SGSIN',
    destinationCoords: [1.28, 103.85],
    departureDate: '2026-09-18T08:00:00Z',
    estimatedArrival: '2026-10-10T14:00:00Z',
    distanceNauticalMiles: 8450,
    distanceCovered: 4890,
    routeWaypoints: [
      [51.95, 4.13],
      [49.50, -4.50],
      [36.00, -6.00],
      [31.26, 32.30],
      [12.50, 43.50],
      [22.45, 68.32],
      [6.00, 80.00],
      [1.28, 103.85]
    ],
    status: 'In Transit',
    captain: 'Capt. Henrik Lindqvist',
    crewCount: 24,
    cargoDescription: '18,500 TEU High Value Electronics, Auto Parts & Industrial Goods',
    fuelEstimatedMT: 2850,
    fuelConsumedMT: 1650,
    fuelCostUSD: 1072500,
    weatherConditions: 'Favorable winds 12 knots, moderate swell 1.5m',
    assignedCargoIds: ['crg_001', 'crg_002'],
    createdAt: new Date('2026-09-10').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_002',
    voyageId: 'VYG-1002',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    originPort: 'Port of Santos',
    originPortCode: 'BRSSZ',
    originCoords: [-23.96, -46.31],
    destinationPort: 'Port of Yokohama',
    destinationPortCode: 'JPYOK',
    destinationCoords: [35.45, 139.65],
    departureDate: '2026-09-02T12:00:00Z',
    estimatedArrival: '2026-10-04T18:00:00Z',
    distanceNauticalMiles: 11200,
    distanceCovered: 10600,
    routeWaypoints: [
      [-23.96, -46.31],
      [-34.00, 18.00],
      [-15.00, 75.00],
      [5.00, 95.00],
      [20.00, 125.00],
      [34.20, 135.10],
      [35.45, 139.65]
    ],
    status: 'In Transit',
    captain: 'Capt. Arthur Pendelton',
    crewCount: 22,
    cargoDescription: '175,000 MT Brazilian Iron Ore Pellets',
    fuelEstimatedMT: 3100,
    fuelConsumedMT: 2950,
    fuelCostUSD: 1917500,
    weatherConditions: 'Slight head-current, clear visibility',
    assignedCargoIds: ['crg_003'],
    createdAt: new Date('2026-08-25').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_003',
    voyageId: 'VYG-1003',
    vesselId: 'vsl_008',
    vesselName: 'MV Global Horizon',
    originPort: 'Port of Shanghai',
    originPortCode: 'CNSHA',
    originCoords: [31.23, 121.47],
    destinationPort: 'Port of Los Angeles',
    destinationPortCode: 'USLAX',
    destinationCoords: [33.74, -118.26],
    departureDate: '2026-09-24T06:00:00Z',
    estimatedArrival: '2026-10-08T20:00:00Z',
    distanceNauticalMiles: 5800,
    distanceCovered: 3450,
    routeWaypoints: [
      [31.23, 121.47],
      [34.00, 140.00],
      [38.00, 170.00],
      [35.00, -150.00],
      [29.80, -140.20],
      [33.74, -118.26]
    ],
    status: 'In Transit',
    captain: 'Capt. Liam O\'Connor',
    crewCount: 26,
    cargoDescription: '22,400 TEU Consumer Retail & Tech Hardware',
    fuelEstimatedMT: 2200,
    fuelConsumedMT: 1250,
    fuelCostUSD: 875000,
    weatherConditions: 'Pacific high pressure ridge, calm sea state 2',
    assignedCargoIds: ['crg_004', 'crg_005'],
    createdAt: new Date('2026-09-15').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_004',
    voyageId: 'VYG-1004',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    originPort: 'Port of Singapore',
    originPortCode: 'SGSIN',
    originCoords: [1.28, 103.85],
    destinationPort: 'Port of Busan',
    destinationPortCode: 'KRPUS',
    destinationCoords: [35.10, 129.04],
    departureDate: '2026-09-27T10:00:00Z',
    estimatedArrival: '2026-10-03T16:00:00Z',
    distanceNauticalMiles: 2500,
    distanceCovered: 1100,
    routeWaypoints: [
      [1.28, 103.85],
      [-8.15, 115.20],
      [10.00, 120.00],
      [25.00, 125.00],
      [35.10, 129.04]
    ],
    status: 'Delayed',
    captain: 'Capt. Tan Wei Ming',
    crewCount: 19,
    cargoDescription: '32,000 MT Precision Machinery & Raw Minerals',
    fuelEstimatedMT: 420,
    fuelConsumedMT: 280,
    fuelCostUSD: 182000,
    delayReason: 'Tropical depression alert near Luzon Strait; speed reduced to 10 knots',
    weatherConditions: 'Gale warning Force 8, swell 4.5m',
    assignedCargoIds: ['crg_006'],
    createdAt: new Date('2026-09-20').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_005',
    voyageId: 'VYG-1005',
    vesselId: 'vsl_009',
    vesselName: 'MT Coral Seaways',
    originPort: 'Port of Jebel Ali (Dubai)',
    originPortCode: 'AEJEA',
    originCoords: [25.01, 55.06],
    destinationPort: 'Port of Valencia',
    destinationPortCode: 'ESVLC',
    destinationCoords: [39.45, -0.32],
    departureDate: '2026-09-12T14:00:00Z',
    estimatedArrival: '2026-10-03T08:00:00Z',
    actualArrival: '2026-10-02T19:30:00Z',
    distanceNauticalMiles: 4950,
    distanceCovered: 4850,
    routeWaypoints: [
      [25.01, 55.06],
      [12.50, 43.50],
      [31.26, 32.30],
      [36.14, -5.35],
      [39.45, -0.32]
    ],
    status: 'In Transit',
    captain: 'Capt. Giuseppe Moretti',
    crewCount: 23,
    cargoDescription: '95,000 MT Ultra Low Sulfur Diesel (ULSD)',
    fuelEstimatedMT: 1100,
    fuelConsumedMT: 1050,
    fuelCostUSD: 682500,
    weatherConditions: 'Mediterranean clear, calm',
    assignedCargoIds: ['crg_007'],
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_006',
    voyageId: 'VYG-1006',
    vesselId: 'vsl_003',
    vesselName: 'MT Arctic Voyager',
    originPort: 'Port of Houston',
    originPortCode: 'USHOU',
    originCoords: [29.74, -95.27],
    destinationPort: 'Port of Rotterdam',
    destinationPortCode: 'NLRTM',
    destinationCoords: [51.95, 4.13],
    departureDate: '2026-09-10T04:00:00Z',
    estimatedArrival: '2026-09-28T12:00:00Z',
    actualArrival: '2026-09-28T11:45:00Z',
    distanceNauticalMiles: 4900,
    distanceCovered: 4900,
    routeWaypoints: [
      [29.74, -95.27],
      [24.50, -82.00],
      [38.00, -50.00],
      [49.00, -10.00],
      [51.95, 4.13]
    ],
    status: 'Completed',
    captain: 'Capt. Valery Morozov',
    crewCount: 25,
    cargoDescription: '165,000 CBM Liquefied Natural Gas (LNG)',
    fuelEstimatedMT: 1400,
    fuelConsumedMT: 1360,
    fuelCostUSD: 952000,
    assignedCargoIds: ['crg_008'],
    createdAt: new Date('2026-08-30').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_007',
    voyageId: 'VYG-1007',
    vesselId: 'vsl_005',
    vesselName: 'MV Nordic Explorer',
    originPort: 'Port of Hamburg',
    originPortCode: 'DEHAM',
    originCoords: [53.54, 9.98],
    destinationPort: 'Port of Felixstowe',
    destinationPortCode: 'GBFXT',
    destinationCoords: [51.95, 1.31],
    departureDate: '2026-10-04T07:00:00Z',
    estimatedArrival: '2026-10-05T14:00:00Z',
    distanceNauticalMiles: 380,
    distanceCovered: 0,
    routeWaypoints: [
      [53.54, 9.98],
      [54.00, 8.00],
      [52.50, 3.50],
      [51.95, 1.31]
    ],
    status: 'Scheduled',
    captain: 'Capt. Jens Sorensen',
    crewCount: 20,
    cargoDescription: '6,200 TEU High-Spec Machinery & Pharma Supplies',
    fuelEstimatedMT: 95,
    fuelConsumedMT: 0,
    fuelCostUSD: 0,
    assignedCargoIds: ['crg_009'],
    createdAt: new Date('2026-09-28').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'vyg_008',
    voyageId: 'VYG-1008',
    vesselId: 'vsl_007',
    vesselName: 'MV Baltic Navigator',
    originPort: 'Port of Santos',
    originPortCode: 'BRSSZ',
    originCoords: [-23.96, -46.31],
    destinationPort: 'Port of Antwerp-Bruges',
    destinationPortCode: 'BEANR',
    destinationCoords: [51.26, 4.38],
    departureDate: '2026-10-06T11:00:00Z',
    estimatedArrival: '2026-10-24T18:00:00Z',
    distanceNauticalMiles: 5400,
    distanceCovered: 0,
    routeWaypoints: [
      [-23.96, -46.31],
      [-5.00, -30.00],
      [20.00, -22.00],
      [48.00, -6.00],
      [51.26, 4.38]
    ],
    status: 'Planned',
    captain: 'Capt. Nikos Papadopoulos',
    crewCount: 21,
    cargoDescription: '78,000 MT Non-GMO Soybeans & Agricultural Meal',
    fuelEstimatedMT: 1250,
    fuelConsumedMT: 0,
    fuelCostUSD: 0,
    assignedCargoIds: ['crg_010'],
    createdAt: new Date('2026-09-29').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedCargo: ICargo[] = [
  {
    _id: 'crg_001',
    cargoId: 'CRG-901',
    voyageId: 'vyg_001',
    voyageCode: 'VYG-1001',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    cargoType: 'Containerized',
    description: 'Electric Vehicle Lithium Battery Packs & High-End Inverters',
    weightTons: 14200,
    containerCount: 1100,
    volumeCBM: 42000,
    shipper: 'Siemens Logistics GmbH',
    consignee: 'Singapore Clean Tech Hub Ltd',
    loadingPort: 'Port of Rotterdam',
    dischargePort: 'Port of Singapore',
    loadingDate: '2026-09-17',
    expectedDelivery: '2026-10-11',
    status: 'In Transit',
    hazardClass: 'IMO Class 9 Dangerous Goods',
    createdAt: new Date('2026-09-12').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_002',
    cargoId: 'CRG-902',
    voyageId: 'vyg_001',
    voyageCode: 'VYG-1001',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    cargoType: 'Refrigerated',
    description: 'Specialty Dairy & European Confectionery Products',
    weightTons: 8500,
    containerCount: 420,
    volumeCBM: 21000,
    shipper: 'FrieslandCampina B.V.',
    consignee: 'Cold Storage Singapore Pte',
    loadingPort: 'Port of Rotterdam',
    dischargePort: 'Port of Singapore',
    loadingDate: '2026-09-17',
    expectedDelivery: '2026-10-11',
    status: 'In Transit',
    createdAt: new Date('2026-09-12').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_003',
    cargoId: 'CRG-903',
    voyageId: 'vyg_002',
    voyageCode: 'VYG-1002',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    cargoType: 'Bulk Grain',
    description: 'High Purity Sintered Iron Ore Feedstock',
    weightTons: 175000,
    volumeCBM: 68000,
    shipper: 'Vale S.A. Brasil',
    consignee: 'Nippon Steel Corporation',
    loadingPort: 'Port of Santos',
    dischargePort: 'Port of Yokohama',
    loadingDate: '2026-09-01',
    expectedDelivery: '2026-10-04',
    status: 'In Transit',
    createdAt: new Date('2026-08-28').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_004',
    cargoId: 'CRG-904',
    voyageId: 'vyg_003',
    voyageCode: 'VYG-1003',
    vesselId: 'vsl_008',
    vesselName: 'MV Global Horizon',
    cargoType: 'Containerized',
    description: 'Consumer Electronics, Smart Displays & Gaming Consoles',
    weightTons: 28000,
    containerCount: 2200,
    volumeCBM: 94000,
    shipper: 'Foxconn Technology Group',
    consignee: 'Best Buy Supply Chain US',
    loadingPort: 'Port of Shanghai',
    dischargePort: 'Port of Los Angeles',
    loadingDate: '2026-09-23',
    expectedDelivery: '2026-10-09',
    status: 'In Transit',
    createdAt: new Date('2026-09-18').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_005',
    cargoId: 'CRG-905',
    voyageId: 'vyg_003',
    voyageCode: 'VYG-1003',
    vesselId: 'vsl_008',
    vesselName: 'MV Global Horizon',
    cargoType: 'Heavy Machinery',
    description: 'Industrial Robotic Arms & CNC Machining Centers',
    weightTons: 14000,
    containerCount: 650,
    volumeCBM: 36000,
    shipper: 'Sany Heavy Industry',
    consignee: 'Caterpillar Inc. USA',
    loadingPort: 'Port of Shanghai',
    dischargePort: 'Port of Los Angeles',
    loadingDate: '2026-09-23',
    expectedDelivery: '2026-10-09',
    status: 'In Transit',
    createdAt: new Date('2026-09-18').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_006',
    cargoId: 'CRG-906',
    voyageId: 'vyg_004',
    voyageCode: 'VYG-1004',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    cargoType: 'Heavy Machinery',
    description: 'Marine Propulsion Replacement Gears & Shafts',
    weightTons: 32000,
    volumeCBM: 41000,
    shipper: 'Wartsila Singapore Hub',
    consignee: 'HD Hyundai Heavy Industries Busan',
    loadingPort: 'Port of Singapore',
    dischargePort: 'Port of Busan',
    loadingDate: '2026-09-26',
    expectedDelivery: '2026-10-04',
    status: 'Delayed',
    createdAt: new Date('2026-09-22').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_007',
    cargoId: 'CRG-907',
    voyageId: 'vyg_005',
    voyageCode: 'VYG-1005',
    vesselId: 'vsl_009',
    vesselName: 'MT Coral Seaways',
    cargoType: 'Refined Petroleum',
    description: 'Ultra-Low Sulfur Diesel (ULSD 10ppm)',
    weightTons: 95000,
    volumeCBM: 112000,
    shipper: 'ADNOC Refining',
    consignee: 'Repsol S.A. Spain',
    loadingPort: 'Port of Jebel Ali (Dubai)',
    dischargePort: 'Port of Valencia',
    loadingDate: '2026-09-11',
    expectedDelivery: '2026-10-03',
    status: 'In Transit',
    createdAt: new Date('2026-09-08').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crg_008',
    cargoId: 'CRG-908',
    voyageId: 'vyg_006',
    voyageCode: 'VYG-1006',
    vesselId: 'vsl_003',
    vesselName: 'MT Arctic Voyager',
    cargoType: 'Liquefied Gas',
    description: 'Cryogenic Liquefied Natural Gas (-162°C)',
    weightTons: 74000,
    volumeCBM: 165000,
    shipper: 'Cheniere Energy Sabine Pass',
    consignee: 'Gate Terminal B.V. Rotterdam',
    loadingPort: 'Port of Houston',
    dischargePort: 'Port of Rotterdam',
    loadingDate: '2026-09-09',
    expectedDelivery: '2026-09-28',
    status: 'Delivered',
    createdAt: new Date('2026-08-31').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedFuelRecords: IFuelRecord[] = [
  {
    _id: 'fl_001',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    voyageId: 'vyg_001',
    voyageCode: 'VYG-1001',
    date: '2026-09-18',
    fuelType: 'VLSFO',
    quantityMT: 450,
    unitPriceUSD: 645,
    totalCostUSD: 290250,
    supplier: 'TotalEnergies Marine Fuels',
    port: 'Port of Rotterdam',
    engineHours: 96,
    distanceTravelledNM: 1720,
    fuelEfficiencyNMPerMT: 3.82,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-20').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'fl_002',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    voyageId: 'vyg_001',
    voyageCode: 'VYG-1001',
    date: '2026-09-25',
    fuelType: 'VLSFO',
    quantityMT: 580,
    unitPriceUSD: 652,
    totalCostUSD: 378160,
    supplier: 'Bunker Holding A/S',
    port: 'Port of Port Said (Suez Canal)',
    engineHours: 120,
    distanceTravelledNM: 2150,
    fuelEfficiencyNMPerMT: 3.71,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-27').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'fl_003',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    voyageId: 'vyg_002',
    voyageCode: 'VYG-1002',
    date: '2026-09-02',
    fuelType: 'VLSFO',
    quantityMT: 850,
    unitPriceUSD: 660,
    totalCostUSD: 561000,
    supplier: 'Petrobras Marine',
    port: 'Port of Santos',
    engineHours: 180,
    distanceTravelledNM: 2800,
    fuelEfficiencyNMPerMT: 3.29,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'fl_004',
    vesselId: 'vsl_008',
    vesselName: 'MV Global Horizon',
    voyageId: 'vyg_003',
    voyageCode: 'VYG-1003',
    date: '2026-09-24',
    fuelType: 'LNG',
    quantityMT: 620,
    unitPriceUSD: 710,
    totalCostUSD: 440200,
    supplier: 'PetroChina Marine Bunkering',
    port: 'Port of Shanghai',
    engineHours: 110,
    distanceTravelledNM: 2400,
    fuelEfficiencyNMPerMT: 3.87,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-26').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'fl_005',
    vesselId: 'vsl_009',
    vesselName: 'MT Coral Seaways',
    voyageId: 'vyg_005',
    voyageCode: 'VYG-1005',
    date: '2026-09-12',
    fuelType: 'VLSFO',
    quantityMT: 410,
    unitPriceUSD: 630,
    totalCostUSD: 258300,
    supplier: 'Emirates National Oil Co (ENOC)',
    port: 'Port of Jebel Ali (Dubai)',
    engineHours: 90,
    distanceTravelledNM: 1450,
    fuelEfficiencyNMPerMT: 3.53,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-14').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'fl_006',
    vesselId: 'vsl_003',
    vesselName: 'MT Arctic Voyager',
    voyageId: 'vyg_006',
    voyageCode: 'VYG-1006',
    date: '2026-09-10',
    fuelType: 'LNG',
    quantityMT: 780,
    unitPriceUSD: 690,
    totalCostUSD: 538200,
    supplier: 'Shell Marine LNG',
    port: 'Port of Houston',
    engineHours: 160,
    distanceTravelledNM: 4900,
    fuelEfficiencyNMPerMT: 6.28,
    recordedBy: 'operator@shipfleet.com',
    createdAt: new Date('2026-09-12').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedMaintenance: IMaintenance[] = [
  {
    _id: 'mnt_001',
    maintenanceId: 'MNT-401',
    vesselId: 'vsl_004',
    vesselName: 'MT Atlantic Pioneer',
    maintenanceType: 'Preventive',
    description: 'Main Engine Cylinder Liner & Fuel Injector Overhaul (25,000 hour cycle)',
    priority: 'High',
    startDate: '2026-09-28',
    expectedCompletion: '2026-10-06',
    technician: 'Drydocks World Dubai Specialist Team',
    costUSD: 78500,
    partsUsed: ['Cylinder Liners x 2', 'Exhaust Valve Spindles', 'High Pressure O-rings'],
    status: 'In Progress',
    notes: 'Parts cleared through Dubai Customs, disassembly 65% complete.',
    createdAt: new Date('2026-09-25').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'mnt_002',
    maintenanceId: 'MNT-402',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    maintenanceType: 'Inspection',
    description: 'Annual Hull Ultrasonic Thickness Measurement & Ballast Tank Inspection',
    priority: 'Medium',
    startDate: '2026-10-08',
    expectedCompletion: '2026-10-11',
    technician: 'ClassNK Marine Surveyors Yokohama',
    costUSD: 14200,
    partsUsed: ['Ultrasonic Probes', 'Calibration Blocks'],
    status: 'Scheduled',
    notes: 'Scheduled immediately upon berth arrival at Yokohama.',
    createdAt: new Date('2026-09-28').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'mnt_003',
    maintenanceId: 'MNT-403',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    maintenanceType: 'Corrective',
    description: 'Turbocharger Bearing Vibration Rectification on Auxiliary Engine #2',
    priority: 'Critical',
    startDate: '2026-09-29',
    expectedCompletion: '2026-10-03',
    technician: 'ABB Turbocharging Service Team',
    costUSD: 32600,
    partsUsed: ['ABB TPS52 Bearing Assembly', 'Lube Oil Filter Elements'],
    status: 'In Progress',
    notes: 'Vessel running with AE#1 and AE#3 safely while servicing.',
    createdAt: new Date('2026-09-29').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'mnt_004',
    maintenanceId: 'MNT-404',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    maintenanceType: 'Inspection',
    description: 'SOLAS Lifeboat & Davit Load Test Certification Renewal',
    priority: 'Low',
    startDate: '2026-09-12',
    expectedCompletion: '2026-09-14',
    actualCompletion: '2026-09-14',
    technician: 'DNV Maritime Certifiers Rotterdam',
    costUSD: 6800,
    partsUsed: ['Water Weight Bags 110%', 'Hydrostatic Release Units'],
    status: 'Completed',
    notes: 'Certified for 12 months with clean audit.',
    createdAt: new Date('2026-09-10').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedCrew: ICrew[] = [
  {
    _id: 'crw_001',
    crewId: 'CRW-201',
    name: 'Henrik Lindqvist',
    role: 'Captain',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    nationality: 'Sweden',
    certification: 'Master Mariner STCW II/2 Unlimited',
    joiningDate: '2025-04-10',
    contractExpiry: '2027-04-10',
    contact: '+46 70 892 1102 / captain@oceanstar.fleetops.com',
    status: 'On Duty',
    createdAt: new Date('2025-04-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crw_002',
    crewId: 'CRW-202',
    name: 'Soren Holst',
    role: 'Chief Engineer',
    vesselId: 'vsl_001',
    vesselName: 'MV Ocean Star',
    nationality: 'Denmark',
    certification: 'Chief Engineer STCW III/2 Unlimited Power',
    joiningDate: '2025-05-15',
    contractExpiry: '2027-05-15',
    contact: '+45 20 481 992 / chiefeng@oceanstar.fleetops.com',
    status: 'On Duty',
    createdAt: new Date('2025-05-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crw_003',
    crewId: 'CRW-203',
    name: 'Arthur Pendelton',
    role: 'Captain',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    nationality: 'United Kingdom',
    certification: 'Master Mariner STCW II/2 Unlimited',
    joiningDate: '2025-02-01',
    contractExpiry: '2026-11-30',
    contact: '+44 7700 900142 / capt.pendelton@pacifictitan.com',
    status: 'On Duty',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crw_004',
    crewId: 'CRW-204',
    name: 'Valery Morozov',
    role: 'Captain',
    vesselId: 'vsl_003',
    vesselName: 'MT Arctic Voyager',
    nationality: 'Estonia',
    certification: 'Master Mariner STCW II/2 Gas Carrier Endorsement',
    joiningDate: '2025-06-10',
    contractExpiry: '2027-06-10',
    contact: '+372 555 41209 / captain@arcticvoyager.fleetops.com',
    status: 'On Duty',
    createdAt: new Date('2025-06-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crw_005',
    crewId: 'CRW-205',
    name: 'Carlos Mendez',
    role: 'Captain',
    vesselId: 'vsl_004',
    vesselName: 'MT Atlantic Pioneer',
    nationality: 'Spain',
    certification: 'Master Mariner STCW II/2 Dangerous Liquid Cargo',
    joiningDate: '2025-03-12',
    contractExpiry: '2027-03-12',
    contact: '+34 612 345 678 / c.mendez@atlanticpioneer.com',
    status: 'On Duty',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'crw_006',
    crewId: 'CRW-206',
    name: 'Tan Wei Ming',
    role: 'Captain',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    nationality: 'Singapore',
    certification: 'Master Mariner STCW II/2 Unlimited',
    joiningDate: '2025-07-01',
    contractExpiry: '2027-07-01',
    contact: '+65 9123 4567 / wm.tan@southerncross.fleetops.com',
    status: 'On Duty',
    createdAt: new Date('2025-06-20').toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedAlerts: IAlert[] = [
  {
    _id: 'alt_001',
    alertType: 'Fuel Low',
    severity: 'Warning',
    message: 'Current fuel reserve for MV Pacific Titan has dropped below 1,000 MT (Remaining: 950 MT). Bunkering needed upon Yokohama arrival.',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    voyageId: 'vyg_002',
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'alt_002',
    alertType: 'Voyage Delayed',
    severity: 'Warning',
    message: 'Voyage VYG-1004 (MV Southern Cross) reported 18-hour ETA setback due to heavy swell in Luzon Strait.',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    voyageId: 'vyg_004',
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'alt_003',
    alertType: 'Maintenance Overdue',
    severity: 'Critical',
    message: 'Annual Auxiliary Turbocharger Overhaul on MV Southern Cross flagged Critical status - immediate technician intervention required.',
    vesselId: 'vsl_006',
    vesselName: 'MV Southern Cross',
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'alt_004',
    alertType: 'Inspection Due',
    severity: 'Info',
    message: 'Annual ClassNK Survey for MV Pacific Titan scheduled within 6 days in Yokohama Port.',
    vesselId: 'vsl_002',
    vesselName: 'MV Pacific Titan',
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const seedAuditLogs: IAuditLog[] = [
  {
    _id: 'aud_001',
    userId: 'usr_admin_001',
    userName: 'Captain Marcus Vance',
    userRole: 'admin',
    action: 'CREATE_VESSEL',
    entity: 'Vessel',
    entityId: 'vsl_001',
    description: 'Registered vessel MV Ocean Star into active commercial fleet inventory',
    ipAddress: '192.168.1.104',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString()
  },
  {
    _id: 'aud_002',
    userId: 'usr_operator_001',
    userName: 'Elena Rostova',
    userRole: 'operator',
    action: 'UPDATE_VOYAGE',
    entity: 'Voyage',
    entityId: 'vyg_1004',
    description: 'Updated route status to Delayed due to weather conditions in Luzon Strait',
    ipAddress: '192.168.1.118',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString()
  },
  {
    _id: 'aud_003',
    userId: 'usr_operator_001',
    userName: 'Elena Rostova',
    userRole: 'operator',
    action: 'LOG_FUEL',
    entity: 'FuelRecord',
    entityId: 'fl_002',
    description: 'Logged 580 MT VLSFO bunkering record for MV Ocean Star at Port Said',
    ipAddress: '192.168.1.118',
    timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString()
  }
];
